"""empty message

Revision ID: 17bbd8818770
Revises: 9798a4472e5b
Create Date: 2020-12-13 15:22:29.217541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17bbd8818770'
down_revision = '9798a4472e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('text', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###
