"""empty message

Revision ID: 276ade30386a
Revises: cbce8aa9c6c8
Create Date: 2020-12-12 20:12:08.553544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276ade30386a'
down_revision = 'cbce8aa9c6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_brief_introduction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=15), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_brief_introduction')
    # ### end Alembic commands ###
