"""empty message

Revision ID: 30d4e9b2e0ec
Revises: 9d7bb6f4c702
Create Date: 2020-12-14 18:47:48.544033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30d4e9b2e0ec'
down_revision = '9d7bb6f4c702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('content', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_brief_introduction', 'content')
    # ### end Alembic commands ###
