"""empty message

Revision ID: 634b19731adc
Revises: 89e6e3b13018
Create Date: 2020-12-14 19:07:25.117070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634b19731adc'
down_revision = '89e6e3b13018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('rates', sa.String(length=20), nullable=True))
    op.add_column('scenic_spots', sa.Column('rates', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenic_spots', 'rates')
    op.drop_column('index_brief_introduction', 'rates')
    # ### end Alembic commands ###
