"""empty message

Revision ID: 815868588adf
Revises: ee52a9238aa8
Create Date: 2020-12-14 20:49:20.193746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815868588adf'
down_revision = 'ee52a9238aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('rates', sa.String(length=20), nullable=False))
    op.add_column('scenic_spots', sa.Column('rates', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenic_spots', 'rates')
    op.drop_column('index_brief_introduction', 'rates')
    # ### end Alembic commands ###
