"""empty message

Revision ID: 89e6e3b13018
Revises: 30d4e9b2e0ec
Create Date: 2020-12-14 18:51:58.221394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89e6e3b13018'
down_revision = '30d4e9b2e0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_brief_introduction', 'rates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('rates', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
