"""empty message

Revision ID: 9798a4472e5b
Revises: 276ade30386a
Create Date: 2020-12-13 15:17:18.641197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9798a4472e5b'
down_revision = '276ade30386a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('text', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'text')
    # ### end Alembic commands ###
