"""empty message

Revision ID: 9d7bb6f4c702
Revises: 17bbd8818770
Create Date: 2020-12-14 18:44:53.875879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d7bb6f4c702'
down_revision = '17bbd8818770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('rates', sa.String(length=20), nullable=False))
    op.drop_column('index_brief_introduction', 'content')
    op.alter_column('info', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    op.alter_column('scenic_spots', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenic_spots', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.alter_column('info', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    op.add_column('index_brief_introduction', sa.Column('content', mysql.MEDIUMTEXT(), nullable=True))
    op.drop_column('index_brief_introduction', 'rates')
    # ### end Alembic commands ###
