"""empty message

Revision ID: c3d0c0ddf636
Revises: f43ff87f8691
Create Date: 2020-12-21 18:49:50.398703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d0c0ddf636'
down_revision = 'f43ff87f8691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('opening_hours', sa.String(length=50), nullable=True))
    op.add_column('scenic_spots', sa.Column('opening_hours', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenic_spots', 'opening_hours')
    op.drop_column('index_brief_introduction', 'opening_hours')
    # ### end Alembic commands ###
