"""empty message

Revision ID: ee52a9238aa8
Revises: 634b19731adc
Create Date: 2020-12-14 20:48:44.312844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee52a9238aa8'
down_revision = '634b19731adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_brief_introduction', 'rates')
    op.drop_column('scenic_spots', 'rates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenic_spots', sa.Column('rates', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('index_brief_introduction', sa.Column('rates', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
