"""empty message

Revision ID: f43ff87f8691
Revises: 174ab37a5742
Create Date: 2020-12-14 21:01:57.247099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43ff87f8691'
down_revision = '174ab37a5742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_brief_introduction', sa.Column('rates', sa.String(length=20), nullable=True))
    op.add_column('scenic_spots', sa.Column('rates', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenic_spots', 'rates')
    op.drop_column('index_brief_introduction', 'rates')
    # ### end Alembic commands ###
